version: '3.8'

services:
  mysql_5:
    image: mysql:5.7.36
    restart: always
    container_name: mysql_5
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - mysql_5:/var/lib/mysql/
    networks:
      - local_net
volumes:
  mysql_5:
    name: mysql_5
networks:
  local_net:
    name: local_net
    driver: bridge
