version: '3.8'

services:
  mysql_8:
    image: mysql:8.0
    restart: always
    container_name: mysql_8
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
     - mysql_8:/var/lib/mysql/
    networks:
      - local_net
volumes:
  mysql_8:
    name: mysql_8
networks:
  local_net:
    name: local_net
    driver: bridge


